src/layout/Header.jsx
src/layout/SimpleHeader.jsx

이미지를 불러오는 경로를 변경하였습니다.
1. 이미지 경로 설정 변경
2. 이미지를 직접 불러오는 방식에서 import로 별칭을 지정하여 불러오는 방식으로 변경

[Header] 이미지 불러오기 변경

---

src/layout/Footer.jsx

이미지를 불러오는 경로를 변경하였습니다.
1. 이미지 경로 설정 변경
2. 이미지를 직접 불러오는 방식에서 import로 별칭을 지정하여 불러오는 방식으로 변경
3. 특수문자 변경

[Footer] 이미지 불러오기 변경

---

src/hooks/useStorage.js
src/pages/Search.jsx
src/store/authStore.js
src/store/searchStore.js
src/utils/getPbImageURL.js
src/utils/keyDown.js
src/utils/removeQuotes.js
src/utils/separateComma.js

일부 유틸 함수를 추가 및 파일명 변경하였습니다.
1. 인증 관련부분 개선을 위해 useStorage.js 및 zustand기반 authStore.js 추가
2. src/utils 내 removeQuotes.js, separateComma.js 추가
3. useSearchStore => searchStore 파일명 변경
4. getPbImageURL,keyDown 함수 export형식을 하단에 export default로 변경

[Common] 일부 유틸 함수 추가 및 파일명 변경

---

public/assets/recommend.svg
src/components/membership/MembershipTable.jsx
src/components/membership/MembershipTitle.jsx
src/components/membership/MembershipType.jsx
src/components/membership/MembershipTypes.jsx
src/components/membership/MembershipWarning.jsx
src/pages/Membership.jsx

멤버십 페이지의 레이아웃을 구현하였습니다.
이 페이지는 별도 기능이 존재하지 않습니다.
1. 멤버십 페이지 구현

[Membership] 멤버십 페이지 레이아웃 구현

---

src/layout/Header.jsx
src/layout/Header.module.css
src/pages/SignIn.jsx
src/store/authStore.js

프로필 이미지에 Hover시, 팝업창 구현
1. 로그인 인증 유지
2. 로그아웃 기능
3. 프로필 / 멤버십 내비게이션 기능

[Header] 프로필 이미지 hover 팝업창 구현

---

public/assets/tving-symbol.svg
src/pages/LoopSlide.jsx
src/pages/OnBoarding.jsx
src/pages/onboarding.module.css
src/styles/index.css

공통 폰트 사이즈 반응형으로 수정, 반응형 레이아웃 수정
1. index.css에 공통으로 폰트 사이즈가 vw에 따라 조정되게 설정
2. 랜딩페이지 경로 문제 수정
3. 랜딩페이지 메인부분 레이아웃 일부 수정 중
크게 달라진 내용이 없어 추후 pr때 사진 첨부 예정

[OnBoarding, 공통] 랜딩 페이지 반응형 레이아웃 일부 수정, 공통 폰트 사이즈 수정

---

src/pages/MovieNav.jsx
src/pages/ProgramNav.jsx

경로 오류가 있는 부분을 수정함
경로상의 오류가 있는 코드를 수정함

[Category] 경로 오류 수정

---

src/pages/LoopSlide.jsx
src/pages/OnBoarding.jsx
src/pages/onboarding.module.css

반응형 레이아웃으로 구현, 이미지 파일 경로 문제와 id 문제 해결
1. 이미지 불러오기 경로 문제 해결
2. 배열에 동일한 key값이 있는 문제 해결
3. 반응형 레이아웃 구현
위 사항과 같습니다.

[OnBoarding] 반응형 수정 및 이미지 파일 오류 수정

---

src/layout/Header.jsx
src/store/authStore.js

렌더링 에러 해결
getPburl 함수를 이용해 사진을 불러오는 함수를 잘못활용하여
렌더링 자체가 안되는 에러가 발생하여 예외처리를 추가하여 조치함

 🐛 [fix] 비동기 데이터 렌더링 에러 해결

---

src/pages/OnBoarding.jsx

merge를 하며 경로를 변경함
버튼 클릭시 signinlist로 이동하도록 경로 변경
보이는 변동 사항 없음

🙌 [merge] 경로 설정 변경

---

src/components/profile/ProfileEditButton.jsx
src/components/profile/ProfileItem.jsx
src/components/profile/ProfileList.jsx
src/components/profile/ProfileTitle.jsx
src/layout/Header.jsx
src/pages/Profile.jsx
src/routes/ProtectRoute.jsx
src/routes/route.jsx

로그인, 프로필 부분이 유지가 안되는 현상이 발생하여
로컬스토리지 키값여부를 통해 유지하게끔 했습니다.
fixes: 리팩토링으로 추후 변동 가능성 있습니다.
- 로컬스토리지 활용 로그인. 프로필 부분 유지

🐛 [fix] 로그인 유지, 프로필 유지 관련 에러

---

src/layout/Header.jsx

username이 불러오기전 참조를 하는 경우로 뜨던
에러를 수정하였습니다.
fixes: 추후 리팩토링으로 변경 가능성 있음
로그인 관련 에러 수정

 🐛 [fix] 로그인 관련 에러 수정

---

src/components/common/SwiperButton.jsx

[Home] 스와이퍼 버튼 컴포넌트 생성

---

src/components/common/SwiperButton.jsx
src/components/home/EventBanner.jsx
src/components/home/Home.module.css
src/components/home/MainBanner.jsx
src/components/home/MainList.jsx
src/components/home/PopularList.jsx
src/pages/Home.jsx
src/store/useContentsStore.js

메인페이지를 컴포넌트 단위로 분리함
메인배너, 인기 드라마와 영화, 스와이퍼 리스트, 이벤트 배너로 분리 후 swiper-button도 컴포넌트로 분리 완료
시각적으로 달라지지 않음

[Home] 메인페이지 컴포넌트 분리

---

src/components/editProfile/ButtonSection.jsx
src/components/editProfile/EditProfileSection.jsx
src/components/editProfile/TitleSection.jsx
src/components/editProfiles/ButtonSection.jsx
src/components/editProfiles/ProfileItem.jsx
src/components/editProfiles/ProfileList.jsx
src/components/editProfiles/ProfileListSection.jsx
src/components/editProfiles/TitleSection.jsx
src/components/profile/Profile.module.css
src/components/profile/ProfileItem.jsx
src/components/profile/ProfileTitle.jsx
src/pages/EditProfile.jsx
src/pages/EditProfiles.jsx
src/pages/Profile.jsx
src/routes/route.jsx

일부 컴포넌트 분리 하였습니다.
fixes: 리팩토링으로 구조 변경 가능성 있음
Related to #69
- 프로필 관련 페이지 일부 분리

 ♻️ [refactor] 프로필 페이지 일부 편집

---

src/components/common/Button/Button.module.css
src/components/common/Button/Buttons.jsx
src/components/editProfile/ButtonSection.jsx
src/components/editProfile/EditProfile.module.css
src/components/editProfile/EditProfileSection.jsx
src/components/editProfiles/ButtonSection.jsx
src/components/editProfiles/EditProfiles.module.css
src/components/editProfiles/ProfileItem.jsx
src/components/editProfiles/ProfileList.jsx
src/components/editProfiles/ProfileListSection.jsx
src/components/profile/Profile.module.css
src/components/profile/ProfileEditButton.jsx
src/components/profile/ProfileItem.jsx
src/components/profile/ProfileList.jsx
src/components/profile/ProfileTitle.jsx
src/layout/Header.jsx
src/layout/RootLayout.jsx
src/pages/EditProfile.jsx
src/pages/EditProfiles.jsx
src/pages/EditProfiles.module.css
src/pages/Profile.jsx
src/pages/SignIn.jsx
src/pages/SignUp.jsx
src/routes/route.jsx

프로필 페이지 컴포넌트 분리 및 모듈 css 적용
1. 프로필 관련 페이지 컴포넌트 분리
2. 프로필 관련 페이지 모듈 css 적용
추후 작성

[Profile] 프로필 페이지 컴포넌트 분리 및 모듈 css 적용

---

src/components/onBoarding/Find.jsx
src/components/onBoarding/JoinMain.jsx
src/components/onBoarding/OnlyTaing.jsx
src/components/onBoarding/QnA.jsx
src/components/onBoarding/Smart.jsx
src/components/onBoarding/StartNow.jsx
src/components/onBoarding/Together.jsx
src/components/onBoarding/Youtube.jsx

경로 설정을 변경하고 오류 해결
1. 컴포넌트 불러오는 방식 변경
2. key prop 오류 해결
사진 없음

[OnBoarding] 경로 문제 및 오류 수정

---

src/components/detail/Contents.module.css
src/components/detail/DetailData.jsx
src/components/detail/EditReview.jsx
src/components/detail/EpisodeToggle.jsx
src/components/detail/RelatedVideo.jsx
src/components/detail/Review.jsx
src/components/detail/ShareLink.jsx
src/components/detail/SimilarVideo.jsx
src/pages/Contents.jsx

상세 페이지 관련 컴포넌트 분리, 파일 추가했습니다.
추후 수정 가능성 있음

[Detail] : 상세페이지 컴포넌트 분리

---

src/App.jsx
src/components/common/PendingPage.jsx

[Exception] 로딩페이지 구현

---

src/components/search/contents/SearchedResultSwiper.jsx

스와이퍼 내비게이션 관련하여 일부 속성을 수정하였습니다.
fixes: 추후 리팩토링으로 구조 변경 가능성 있음
- 스와이퍼 일부 속성 변경

[Search] 스와이퍼 일부 수정

---

src/components/common/Spinner.jsx

[Exception] Spinner 스타일 변경

---

src/components/category/MovieNav.jsx
src/components/category/NavButton.jsx
src/components/category/ProgramNav.jsx

swiper button이 변함에 따른 수정
1. swiper button 변화에 따른 컴포넌트 변경
2. prop-types 오류 수정
사진 없음

[Category] swiper button 관련 수정

---

src/components/detail/DetailData.jsx
src/components/detail/EditReview.jsx
src/components/detail/RelatedVideo.jsx
src/components/detail/Review.jsx
src/components/detail/ShareLink.jsx
src/components/detail/SimilarVideo.jsx
src/pages/Contents.jsx
src/pages/Favorite.jsx
src/pages/Favorite.module.css
src/styles/index.css

내찜콘 기능 구현
하트 클릭시 포켓베이스의 유저에 프로그램 정보가 등록되고 해당 프로그램이 찜 목록에 렌더링

[Detail] 내가 찜한 콘텐츠 기능 구현 

---

src/pages/Membership.jsx

멤버십 페이지에 메타 태그를 추가하였습니다.
fixes: 리팩토링으로 추후 변동 가능성 있음
- 메타태그 추가

[membership] 멤버십 페이지 메타 태그 추가

---

src/components/detail/Review.jsx
src/pages/Contents.jsx
src/pages/Favorite.jsx

[Detail] 메타 태그 수정

---

src/layout/Header.jsx
src/pages/EditProfile.jsx
src/pages/EditProfiles.jsx
src/pages/Profile.jsx

프로필 관련 페이지 메타태그를 추가하였습니다.
그리고 헤더의 프로필모달 부분을 일부 수정하였습니다.
fixes: 추후 리팩토링으로 구조 변경 가능성 있음
- 프로필 관련 페이지 메타태그를 추가

[profile] 프로필 관련 페이지 메타태그 추가

---

src/components/snslogin/SnsLogin.jsx
src/components/snslogin/SnsLogin.module.css
src/pages/SignIn.jsx
src/pages/SignInList.jsx

sns 로그인 페이지에서 카카오톡 연동 로그인 시 다른 화면으로
이동하지 않고 멈춰있는 현상을 수정하고, 레이아웃이 미적용되는 문제로
분리하지 않았던 요소에 컴포넌트 적용을 완료했습니다
Fixes: 추후 성능 개선을 위한 수정 가능
1. 카카오톡 로그인 성공시 프로필 선택 창으로 이동 부분 추가
2. SnsLoginButton 로 분리 가능한 요소를 모두 분리
기존 레이아웃 에서 변경점 없음

♻️ [feat]	sns 로그인 페이지 컴포넌트 수정 및 누락 기능 보완

---

src/components/header/Header.module.css

프로필 이미지 비율 수정
프로필 이미지의 비율이 1:1로 나타나지 않는 점을 수정함.
사진 없음

🐛 [fix] 프로필 이미지 비율 수정

---

index.html
src/components/editProfile/EditProfileSection.jsx
src/components/editProfiles/ProfileItem.jsx
src/components/editProfiles/ProfileList.jsx
src/components/editProfiles/ProfileListSection.jsx
src/components/profile/ProfileItem.jsx
src/components/profile/ProfileList.jsx

프로필 부분 주석, 콘솔 삭제 했습니다.
- 주석, 콘솔 삭제

 [profile] 주석, 콘솔 삭제

---

src/components/search/contents/ListSection.jsx
src/components/search/contents/RealtimeSearch.jsx
src/components/search/contents/RecentView.jsx
src/components/search/contents/SearchResult.jsx
src/components/search/contents/SearchSection.jsx
src/components/search/contents/SearchedResultSwiper.jsx

검색 페이지 부분 주석, 콘솔 삭제 했습니다.
- 주석, 콘솔 삭제

[search] 주석, 콘솔 삭제

---

src/components/detail/DetailData.jsx
src/components/detail/EditReview.jsx
src/components/detail/Review.jsx
src/components/detail/ShareLink.jsx
src/components/detail/SimilarVideo.jsx
src/pages/Favorite.jsx

[Detail]  상세페이지 코드 수정
